version: '3.8'

services:
  
  app:
    build: ./docker/symfony
    container_name: manager_tool_app_container
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000
  
  nodejs:
    build: ./docker/nodejs
    container_name: manager_tool_nodejs_container
    depends_on:
      - app
    volumes:
      - .:/app
  
  db:
    image: postgres:13-alpine
    container_name: manager_tool_db_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  adminer:
    image: adminer
    container_name: manager_tool_adminer_container
    depends_on:
      - db
    ports:
      - 8080:8080